name: Run Code Review for Pull Requests

on:
  pull_request:
    branches:
      - '**'
permissions: write-all
jobs:
  code_review:
    name: Run code review for a pull request
    runs-on: ubuntu-latest
    container:
      image: mingc/android-build-box:1.28.0 # You might need to check further versions: https://github.com/mingchen/docker-android-build-box/tags
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        run: |
          apt-get update
          apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt-get install -y nodejs
      
      - name: Clone AI code review repository
        run: git clone ${{ secrets.AI_CODE_REVIEW_GIT_AUTH }} ./ai-code-reviewer
      
      - name: Copy and run the code review script
        env:
          CODE_REVIEWER_GITHUB_ACCESS_TOKEN: ${{ secrets.CODE_REVIEWER_GITHUB_ACCESS_TOKEN }}
          AI_CODE_REVIEW_PROJECT: ${{ secrets.AI_CODE_REVIEW_PROJECT }}
          CURRENT_REPO_ACCESS_GIT_URL: ${{ secrets.CURRENT_REPO_ACCESS_GIT_URL }}
          SONAR_PACKAGE_FILE: ${{ secrets.SONAR_PACKAGE_FILE }}
        run: |
          if [ -n "$SONAR_PACKAGE_FILE" ]; then
            printf '%s' "$SONAR_PACKAGE_FILE" | base64 --decode > package.json
          fi
          jenv global 17
          cp -r ./ai-code-reviewer/run_code_review.sh .
          chmod +x ./run_code_review.sh
          ./run_code_review.sh